### ISSUE TITLE
Channel order tracker

### ISSUE THREAD

**Issue by ericthelemur** [UWCS/apollo#104]
There have been a few cases of exec accidentally reordering channels, without noticing. To mitigate this, have Apollo check this order, and notify (exec) on a change. 

Note: having Apollo automatically undo the change would be a problem for purposeful changes

**Comment by Jlobblet** [comment]
Automatic undo is probably more of a faff than it's worth to implement. Provided the notification is descriptive enough, should be easy for exec to revert. Discord API exposes the position of a channel as a number - could work out its neighbours before and then say "between #channel-1 and #channel-2" fairly easily.
