### ISSUE TITLE
Misc commands: Add links to !issue, !pr and others

### ISSUE THREAD

**Issue by ericthelemur** [UWCS/apollo#179]
- [x] Add link to issue page to !issue
- [x] Same for !pr
- [x] Update !merge to be not John anymore
- [x] Remove !blueshell?
- [x] Move !servers to read from config
- [ ] #130 Add hyphens as alias as well as dashes

**Comment by Joeyh021** [comment]
The first 3 can probably be part of a GitHub cog. I have one or two other ideas for that two, mainly linking to PRs/Issues with hashtags like #179
