### ISSUE TITLE
!tldr Private View

### ISSUE THREAD

**Issue by jfitz02** [UWCS/apollo#260]
It may be nice to have the option to privately get the tldr of a conversation without interrupting the convo.
This should be a simple change of adding the kwarg ephemeral=True when the user wants it to be private

[Ephemeral Link](https://discordpy.readthedocs.io/en/latest/interactions/api.html#:~:text=ephemeral%20(bool)%20%E2%80%93%20Indicates%20if%20the%20message%20should%20only%20be%20visible%20to%20the%20user%20who%20started%20the%20interaction.%20If%20a%20view%20is%20sent%20with%20an%20ephemeral%20message%20and%20it%20has%20no%20timeout%20set%20then%20the%20timeout%20is%20set%20to%2015%20minutes.)

**Comment by jfitz02** [comment]
Note that the private field only work with slash commands
so if someone uses it without slash commands it will not be private. but neither would the request so i think thats fine

**Comment by raven0034** [comment]
Agree with this suggestion.
