### ISSUE TITLE
Tex rendering fails silently

### ISSUE THREAD

**Issue by dixonary** [UWCS/apollo#38]
Occasionally tex rendering will begin and then fail before sending the rendered document.

(Possibly related and automatically fixed by #37)

**Comment by Jlobblet** [comment]
Test case: `$n^{\frac{1}{\log{\log{n}}}}$`

**Comment by samcoy3** [comment]
Another test case: `$2^{O(\sqrt{\log n \log \log n})}$`. My instinct is that it's something to do with weird heights? Both examples I've seen have complicated exponents.

**Comment by the-Bruce** [comment]
A few minimal test cases I've managed to find are `$1^\frac12$` and `$1^{1^1}$`, but things like `$\frac{1^2}{2}$` don't. The actual error is thrown from within the image saving routine (https://github.com/UWCS/apollo/blob/0db0711a924b8cd1485c88ccd89a5a52e0ace452/cogs/commands/tex.py#L98) with a index error, which makes me think it might be to do with the cropping algorithm immediately preceding it.
