### ISSUE TITLE
Karma parsing is too lax

### ISSUE THREAD

**Issue by dixonary** [UWCS/apollo#63]
The karma parser should only recognise lexemes where the karma operators are suffixes.

Currently it will parse any nonempty string followed by `++`,`+-`,`-+`,`--`, which is too generous as these appear often in other contexts such as links.

**Comment by Jlobblet** [comment]
Enforced certain characters after an operator in 1d8209262bef7a58842fae724b4297f403a5c475. Currently, these are provided by the following regex:
https://github.com/UWCS/apollo/blob/48a1656540e8ed2953cd11c6e69a3f7ba43f2ff0/karma/parser.py#L49

Open to feedback about what the allowed set of characters should be.

**Comment by dixonary** [comment]
I think those are the reasonable visible characters from ASCII. Obviously unicode has its own selection of whitespace characters, and ascii has separators, but that may be overkill.

So long as it doesn't include any characters that appear in youtube URLs or base64-encoded strings I think it should be fine.
